import type { Template } from './types'

export const templates: Template[] = [
  {
    id: 'dark-komi',
    name: 'Dark Komi',
    description: 'Dark, cinematic, lime green accent',
    colors: {
      background: '#0a0a0a',
      surface: '#161616',
      text: '#ffffff',
      muted: 'rgba(255,255,255,0.45)',
      accent: '#c8ff00',
      border: 'rgba(255,255,255,0.08)',
    },
    fonts: {
      display: "'Big Shoulders Display', sans-serif",
      body: "'DM Sans', sans-serif",
    },
    grain: true,
    category: 'dark',
    layout: {
      heroStyle: 'cover-photo',
      cardRadius: '0.875rem',
      socialStyle: 'icons-only',
      nameSize: 'xl',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean, white, professional',
    colors: {
      background: '#fafafa',
      surface: '#ffffff',
      text: '#111111',
      muted: 'rgba(0,0,0,0.45)',
      accent: '#111111',
      border: 'rgba(0,0,0,0.08)',
    },
    fonts: {
      display: "'Inter', sans-serif",
      body: "'Inter', sans-serif",
    },
    grain: false,
    category: 'light',
    layout: {
      heroStyle: 'circle-avatar',
      cardRadius: '0.875rem',
      socialStyle: 'pills',
      nameSize: 'md',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm, Ibiza vibes, ocean blue accent',
    colors: {
      background: '#0a1628',
      surface: '#0f1f3a',
      text: '#ffffff',
      muted: 'rgba(255,255,255,0.5)',
      accent: '#4d9fff',
      border: 'rgba(255,255,255,0.1)',
    },
    fonts: {
      display: "'Big Shoulders Display', sans-serif",
      body: "'DM Sans', sans-serif",
    },
    grain: true,
    category: 'dark',
    layout: {
      heroStyle: 'circle-avatar',
      cardRadius: '999px',
      socialStyle: 'pills',
      nameSize: 'lg',
    },
  },
  {
    id: 'festival',
    name: 'Festival',
    description: 'Energetisch, bunt, orange accent',
    colors: {
      background: '#1a0a00',
      surface: '#261200',
      text: '#ffffff',
      muted: 'rgba(255,255,255,0.5)',
      accent: '#ff6b00',
      border: 'rgba(255,107,0,0.15)',
    },
    fonts: {
      display: "'Big Shoulders Display', sans-serif",
      body: "'DM Sans', sans-serif",
    },
    grain: true,
    category: 'dark',
    layout: {
      heroStyle: 'cover-photo',
      cardRadius: '0.875rem',
      socialStyle: 'icons-only',
      nameSize: 'xl',
    },
  },
  {
    id: 'techno',
    name: 'Techno',
    description: 'Industrial, Berlin, purple accent',
    colors: {
      background: '#0d0d0d',
      surface: '#1a1a1a',
      text: '#e0e0e0',
      muted: 'rgba(255,255,255,0.4)',
      accent: '#a855f7',
      border: 'rgba(168,85,247,0.12)',
    },
    fonts: {
      display: "'Space Grotesk', sans-serif",
      body: "'DM Sans', sans-serif",
    },
    grain: true,
    category: 'dark',
    layout: {
      heroStyle: 'cover-photo',
      cardRadius: '0.5rem',
      socialStyle: 'icons-only',
      nameSize: 'xl',
    },
  },
  {
    id: 'vintage',
    name: 'Vintage',
    description: 'Analog, warm, braun — für Gastro & Cafés',
    colors: {
      background: '#f5f0e8',
      surface: '#fffdf7',
      text: '#3d2e1e',
      muted: 'rgba(61,46,30,0.5)',
      accent: '#a0522d',
      border: 'rgba(61,46,30,0.1)',
    },
    fonts: {
      display: "'DM Serif Display', serif",
      body: "'DM Sans', sans-serif",
    },
    grain: false,
    category: 'light',
    layout: {
      heroStyle: 'circle-avatar',
      cardRadius: '0.875rem',
      socialStyle: 'pills',
      nameSize: 'md',
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Club vibes, neon pink accent',
    colors: {
      background: '#0a0a14',
      surface: '#12121f',
      text: '#ffffff',
      muted: 'rgba(255,255,255,0.45)',
      accent: '#ff2d95',
      border: 'rgba(255,45,149,0.12)',
    },
    fonts: {
      display: "'Big Shoulders Display', sans-serif",
      body: "'DM Sans', sans-serif",
    },
    grain: true,
    category: 'dark',
    layout: {
      heroStyle: 'cover-photo',
      cardRadius: '999px',
      socialStyle: 'icons-only',
      nameSize: 'xl',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Outdoor, natürlich, grün accent',
    colors: {
      background: '#0a1a0a',
      surface: '#112211',
      text: '#e8f0e8',
      muted: 'rgba(232,240,232,0.5)',
      accent: '#4ade80',
      border: 'rgba(74,222,128,0.1)',
    },
    fonts: {
      display: "'Space Grotesk', sans-serif",
      body: "'DM Sans', sans-serif",
    },
    grain: true,
    category: 'dark',
    layout: {
      heroStyle: 'circle-avatar',
      cardRadius: '0.875rem',
      socialStyle: 'pills',
      nameSize: 'lg',
    },
  },
  {
    id: 'desert',
    name: 'Desert',
    description: 'Warm, sand, orange-gold accent',
    colors: {
      background: '#1a1408',
      surface: '#241e10',
      text: '#f5e6cc',
      muted: 'rgba(245,230,204,0.5)',
      accent: '#e6a520',
      border: 'rgba(230,165,32,0.1)',
    },
    fonts: {
      display: "'Big Shoulders Display', sans-serif",
      body: "'DM Sans', sans-serif",
    },
    grain: true,
    category: 'dark',
    layout: {
      heroStyle: 'cover-photo',
      cardRadius: '0.875rem',
      socialStyle: 'icons-only',
      nameSize: 'lg',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Tief, blau, cyan accent',
    colors: {
      background: '#050e18',
      surface: '#0a1825',
      text: '#e0f0ff',
      muted: 'rgba(224,240,255,0.45)',
      accent: '#22d3ee',
      border: 'rgba(34,211,238,0.1)',
    },
    fonts: {
      display: "'Space Grotesk', sans-serif",
      body: "'DM Sans', sans-serif",
    },
    grain: true,
    category: 'dark',
    layout: {
      heroStyle: 'circle-avatar',
      cardRadius: '999px',
      socialStyle: 'pills',
      nameSize: 'lg',
    },
  },
]

export function getTemplate(id: string): Template {
  return templates.find(t => t.id === id) ?? templates[0]
}

export function getTemplateCSSVars(template: Template): Record<string, string> {
  return {
    '--bg': template.colors.background,
    '--surface': template.colors.surface,
    '--text': template.colors.text,
    '--muted': template.colors.muted,
    '--accent': template.colors.accent,
    '--border': template.colors.border,
    '--font-display': template.fonts.display,
    '--font-body': template.fonts.body,
    '--card-radius': template.layout.cardRadius,
  }
}
